# TODO: Build vue stage

# Build golang stage
FROM golang:1.8 as frpBuild

COPY . /go/src/github.com/fatedier/frp

ENV CGO_ENABLED=0

RUN cd /go/src/github.com/fatedier/frp \
    && make -f ./Makefile.cross-compiles

# Run docker image
FROM armhf/alpine

COPY --from=frpBuild /go/src/github.com/fatedier/frp/frpc_linux_arm /frpc
COPY --from=frpBuild /go/src/github.com/fatedier/frp/conf/frpc.ini /
COPY --from=frpBuild /go/src/github.com/fatedier/frp/entrypoint/frpc.sh /entrypoint.sh

RUN mkdir /frp
RUN echo "EDT" > /frp/username

WORKDIR /

CMD ["./entrypoint.sh"]
