# TODO: Build vue stage

# Build golang stage
FROM golang:1.8 as frpBuild

COPY . /go/src/github.com/fatedier/frp

ENV CGO_ENABLED=0

RUN cd /go/src/github.com/fatedier/frp \
    && make

# Run docker image
FROM alpine:3.6
COPY --from=frpBuild /go/src/github.com/fatedier/frp/bin/frps /
COPY --from=frpBuild /go/src/github.com/fatedier/frp/conf/frps.ini /
COPY --from=frpBuild /go/src/github.com/fatedier/frp/entrypoint/frps.sh /entrypoint.sh

EXPOSE 80 443 6000 7000 7500

WORKDIR /

CMD ["./entrypoint.sh"]
